### ISSUE TITLE
Overview of the tasks open with Alt-Tab is postponed

### ISSUE THREAD

**Issue by joerrg** [linuxmint/mint21.1-beta#31] opened 2022-12-08 18:22 UTC
Since Release 21 the task overview with Alt+Tab is postponed respectively squeezed when I have 14 tasks open. It depends of the native resolution of the monitor. Also in the Beta of 21.1.  In version 20.3. it was ok.
On my Desktop with its native resolution of 1920*1200, the overview is ok when less of 13 or 15 and more tasks are open. But if 14 tasks open the overview looks postponed.
I use the standard theme of Mint an have no special settings in the "windows"-dialog "alt-tab".

**Comment by NintendoManiac64** [comment] 2022-12-08 18:35
While I'm not part of the dev team, I must ask if your use of "postponed" is what you indeed intend - are you saying the appearance of the overview is delayed, or are you saying something else?

(the main confusion is due to your statement of "Alt+Tab is postponed respectively squeezed" which does not make sense to me grammatically)

**Comment by joerrg** [comment] 2022-12-08 18:41
Sorry for confusion. I mean the apperance of the overview of the open tasks which is shown if you press Alt+Tab: this overview of the tasks is postponed. Depending of the resolution, in my case 1920*1080

**Comment by the-allanc** [comment] 2022-12-11 14:02
I realise that I've also reported this issue as #63 - there's a screenshot there.

**Comment by clefebvre** [comment] 2022-12-12 17:00
Yep, alt-tab squashed. Confirmed duplicate of #63

**Closed as completed by clefebvre** 2022-12-12 17:00 UTC
