### ISSUE TITLE
When you right-click on an iso in nemo and choose to make a bootable usb stick, then you have to select the iso manually again!

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mint21.1-beta#11] opened 2022-12-05 18:01 UTC
But there's another issue here: When you right-click and choose to make a bootable usb stick, then you have to select the iso manually again!

_Originally posted by @carlosmintfan in https://github.com/linuxmint/mint21.1-beta/issues/8#issuecomment-1337863031_

**Comment by mtwebster** [comment] 2022-12-05 20:00
Same root cause as #8, closing

**Closed as completed by mtwebster** 2022-12-05 20:00 UTC
