### ISSUE TITLE
cinnamon: Alt+tab popup can look misaligned

### ISSUE THREAD

**Issue by the-allanc** [linuxmint/mint21.1-beta#63] opened 2022-12-11 13:10 UTC
With a certain number of windows open (14 on my machine), the window popup looks bad - there's a big blank space on the right, and the highlighting around the icon seems to be misaligned.

![bad-alt-tab](https://user-images.githubusercontent.com/4016213/206905461-72a743fe-70d3-48aa-9c44-0fc01490d042.png)

**Comment by clefebvre** [comment] 2022-12-12 15:35
Confirmed bug since Cinnamon 5.4.

**Comment by clefebvre** [comment] 2022-12-15 13:20
I'd love to get that fixed for STABLE. I also know we tried to fix it before and we came short. It wasn't easy. We'll need to take our time and go at it again. Marking this as to be fixed later.

**Closed as completed by clefebvre** 2022-12-15 13:20 UTC
Labels: bug
