### ISSUE TITLE
Mozilla VPN Mint 21.1-Beta 

### ISSUE THREAD

**Issue by gh4wi** [linuxmint/mint21.1-beta#66] opened 2022-12-11 15:40 UTC
The Mozilla VPN site provides 3 apt commands to install the VPN on Ubuntu like versions of Linux.
These commands work fine on Mint 20.3 and provide a working PPA and Authentication Key to Update Manager.

On Mint 21.1-Beta these commands provide an old version (2.2) of Mozilla VPN.
When started, the VPN wants to do an update but cannot as there is no Authentication Key in Update Manager.
There is a PPA added to Update Manager, but NO Authentication Key ???

**Comment by clefebvre** [comment] 2022-12-15 13:27
Duplicate of https://github.com/linuxmint/mint21.1-beta/issues/20. Fixed in mintsources 2.2.1.

**Closed as completed by clefebvre** 2022-12-15 13:27 UTC
