### ISSUE TITLE
cinnamon: Brightness applet and keys stop working

### ISSUE THREAD

**Issue by Rockets31** [linuxmint/mint21.1-beta#67] opened 2022-12-11 17:01 UTC
In LM-20.3 it is possible setting "real" 1%-brigthness value and the slider works direct & smoothly, in LM-21.1 it "jitters". What about adding a configuration-menu for changing slider-steps (**applet.js**: line 196 & line 223: "this._step = .01;"). This works pretty good in LM-20.3 power-applet and brightness-keys always work, so one also could turn backlight on/off!

**1. Observation:**

Brightness-slider of power-applet disappears after cinnamon-restart & Brightness-keys won`t work anymore (running on notebook)

**2. Expectation:**

Brightness-slider should not disappear, but shows correct brightness-value

**3. Reproduction:**

 a. Set brightness-slider by power-applet to "Brightness: 0%"

 b. Go to "sys/class/backlight/intel_backlight" (Intel-card) **or** "sys/class/backlight/acpi_video0" (ATI-card)

 c. Open "actual_brightness" file and notice actual-brightness-value

 d. Open "max_brightness" file and notice maximum-brightness-value

 e. Divide actual-brightness-value by maximum-brightness-value: 0,02 = 2%

 f. Calculate brightness-value for 1%:
   
    Divide max_brightness-value by 100 -> you got brightness-value for 1%, e.g. "240"

 g. Set 1% brightness-value by terminal:
   
    sudo -s

    echo 240 > /sys/class/backlight/intel_backlight/brightness   #Intel-card

    echo 240 > /sys/class/backlight/acpi_video0/brightness       #ATI-card

 h. Restart Cinnamon

 i. Click power-applet by left-mouse-button: Brightness-slider is gone & Brightnes-key won't work anymore

**Comment by clefebvre** [comment] 2022-12-15 13:59
The applet won't let you go below 2%. That's by design. On some computers this actually turns the screen completely off and the user can't see anything anymore. So the applet's 0% is actually 2% of real brightness.

Anyhow, there's another issue at play here apparently. I assume something is crashing for the applet not to show up and the brightness keys not to react. Can you check the Cinnamon logs in ~/.xsession-errors, as we all Looking Glass logs (Alt-F2, then type lg, then type enter, then click on Log).

And last but not least, I'd like to know if csd-power is still running: 

`ps -ef | grep csd-power`

**Comment by clefebvre** [comment] 2022-12-15 14:00
I'm marking this to be fixed later and closing it. Please continue to provide feedback though. This will be looked at post-release.

**Closed as completed by clefebvre** 2022-12-15 14:00 UTC
Labels: will-fix-later

**Comment by Rockets31** [comment] 2022-12-17 14:55
Here i got some information for you. I booted into LM-21.1, set brightness to 1%-percentage, restarted cinnamon and "**ps -ef | grep csd-power**":

~$ sudo -s        
# echo 240 > /sys/class/backlight/intel_backlight/brightness
# ps -ef | grep csd-power
rocket     1359    1071  0 15:19 ?        00:00:00 csd-power
root        2242    2064  0 15:25 pts/1    00:00:00 grep --color=auto csd-power
# 

**xsession-errors-log:**
[xsession-errors.txt](https://github.com/linuxmint/mint21.1-beta/files/10251950/xsession-errors.txt)

**Melange-Log:**
[melange-log.txt](https://github.com/linuxmint/mint21.1-beta/files/10251954/melange-log.txt)

I think, he is complaining about minimum-limitation of 2%-percentage - kind of a "out of boarder" error... Have fun :-)
