### ISSUE TITLE
On some specific programs, whether maximized or un-maximized, you can double-click in-between the close button and the most top-right corner to maximize & un-maximize the window

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21.1-beta#74] opened 2022-12-12 19:53 UTC
(occurs on Cinnamon, Mate, and Xfce but, since the Xfce Settings Editor is one of the programs in question, it made sense to demonstrate using Xfce)

To be clear, you don't have *only* the ability to double-click in that area between the close button and the most top-right corner, but that's the function that makes it the most obvious since, otherwise, you'd expect the program window to instead just close as soon as you left-click.

**EDIT**: To be double-clear, I was simply using the double-click action to demonstrate that, for whatever reason on some programs, there's a sort of "empty space" between the close button and the most top-right corner that doesn't exist in some other programs (the software manager at the end of the video is one such example where I show that it lacks this aforementioned "empty space").

And, to spell it out, any of those programs that have this "empty space" cannot be closed when maximized by putting the cursor in the most top-right corner of your screen like you can do with programs that don't have this "empty space" (again, the software manager at the end of the video demonstrates how clicking in the most top-right corner when maximized *does* close it).

[video.webm](https://user-images.githubusercontent.com/11896003/207140681-42ee2e7d-523c-44ba-a312-ec9329b76a04.webm)

**Comment by anaximeno** [comment] 2022-12-12 20:13
This doesn't seem to be a bug. If you go to the system settings inside the window section you'll find an option to configure the behavior when clicking two times on the window's header.

**Comment by NintendoManiac64** [comment] 2022-12-12 23:02
> This doesn't seem to be a bug. If you go to the system settings inside the window section you'll find an option to configure the behavior when clicking two times on the window's header.

That's not the point of what I was trying to convey - I was simply using the double-click action to demonstrate that, for whatever reason on some programs, there's a sort of "empty space" between the close button and the most top-right corner that doesn't exist in some other programs (the software manager at the end of the video is one such example where I show that it lacks this aforementioned "empty space").

To spell it out, any of those programs that have this "empty space" cannot be closed when maximized by putting the cursor in the most top-right corner of your screen like you can do with programs that don't have this "empty space" (again, the software manager at the end of the video demonstrates how clicking in the most top-right corner when maximized does close it).

**Comment by clefebvre** [comment] 2022-12-13 12:42
OK, it looks like titlebar apps (SSD windows in other words) can be closed by having the pointer all the way to the top right corner of the screen when the window is maximized.

But headerbar apps (CSD windows) cannot. They have a gap so you interact with the headerbar instead of the close button.

**Comment by clefebvre** [comment] 2022-12-13 12:45
I can reproduce this also with Adwaita and it's more visible there (the close button has a highlight effect which is more visible). This looks upstream and in the design of headerbars imo. Please report it to GTK directly.

**Closed as completed by clefebvre** 2022-12-13 12:45 UTC
