### ISSUE TITLE
Small translation problem for "corner bar" and "update manager"

### ISSUE THREAD

**Issue by roxfr** [linuxmint/mint21.1-beta#95] opened 2022-12-16 20:46 UTC
Hello,
There are missing translations for corner bar and update manager.
See pictures below.
Regards,
Roxfr

**corner bar**

![01](https://user-images.githubusercontent.com/52124613/208186035-b1379f40-41c3-4cfb-93af-af0c8f5edf05.png)

![02](https://user-images.githubusercontent.com/52124613/208186052-1a5284b6-1554-480a-89ad-a80cb643afcb.png)

![03](https://user-images.githubusercontent.com/52124613/208186070-25974822-0ef2-40c5-910d-a6bec60c60e5.png)

**update manager**

![01](https://user-images.githubusercontent.com/52124613/208188168-689a7881-2cb6-4b54-9f13-59be9913308b.png)

![02](https://user-images.githubusercontent.com/52124613/208188183-74fe4ab8-4769-4035-9dbb-476089e61af4.png)

**Comment by clefebvre** [comment] 2022-12-16 23:30
Duplicate of https://github.com/linuxmint/mint21.1-beta/issues/1

**Closed as completed by clefebvre** 2022-12-16 23:30 UTC
